apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Infracloud
  default: Infracloud org
spec:
  type: organization
  profile:
    displayName:  Infracloud
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [Infracloud]